# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c21e6d8285bea9abfcad4ddb62d2be01a58cb5d0712c3b6b1a3f1e691e1b1f0da68733e2fa0d791029591f53dfcee2f6f3e488180f9d8c9877087e60d5637d1e

test:
  secret_key_base: f9c38d0e969712329912c90ac4f0d482188712083f34a35987ee0a3e3e18e24a6a706e2429de0f2891a0c11a051a7d92b29c7763382cc49a68e352c820ca3815

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
